#/opt/monitoring/docker-compose2.yml

version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    restart: unless-stopped
    user: "10001:10001"
    ports:
      - "3100:3100"
    volumes:
      - /opt/loki/config:/etc/loki
      - /opt/loki/data:/opt/loki/data
    command: -config.file=/etc/loki/loki.yml

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    restart: unless-stopped
    depends_on:
      - loki
    volumes:
      - /var/log:/var/log:ro
      - /opt/promtail/config:/etc/promtail
      - /usr/local/x-ui:/usr/local/x-ui:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /run/log/journal:/run/log/journal:ro
      - /var/log/journal:/var/log/journal:ro
    command: -config.file=/etc/promtail/promtail.yml

  process-exporter:
    image: ncabatoff/process-exporter:latest
    container_name: process-exporter
    restart: unless-stopped
    privileged: true
    pid: "host"
    ports:
      - "9256:9256"
    volumes:
      - /proc:/host/proc:ro
      - /opt/process-exporter/config:/config:ro
    command:
      - --procfs=/host/proc
      - --config.path=/config/process-exporter.yml