global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: "node_185_233_80_240"
    static_configs:
      - targets: ["185.233.80.240:9100"]

  - job_name: "3xui_185_233_80_240"
    static_configs:
      - targets: ["185.233.80.240:9300"]

rule_files:
  - /etc/prometheus/rules/*.yml