server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: varlogs
    static_configs:
      - targets: [localhost]
        labels:
          job: varlogs
          host: th3rshifter
          __path__: /var/log/*.log

  - job_name: fail2ban
    static_configs:
      - targets: [localhost]
        labels:
          job: fail2ban
          host: th3rshifter
          __path__: /var/log/fail2ban.log

  - job_name: journald
    journal:
      max_age: 12h
      labels:
        job: journald
        host: th3rshifter
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        regex: '(fail2ban\.service|xray\.service|3x-ui\.service)'
        action: keep
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'